"use client";

import { useState, useEffect } from "react";
import {
    Key,
    User,
    Calendar,
    Activity,
    MoreHorizontal,
    ShieldAlert,
    Ban,
    CheckCircle2,
    ChevronLeft,
    ChevronRight,
    Loader2,
    Clock
} from "lucide-react";
import {
    Table,
    TableBody,
    TableCell,
    TableHead,
    TableHeader,
    TableRow
} from "@/components/ui/table";
import {
    DropdownMenu,
    DropdownMenuContent,
    DropdownMenuItem,
    DropdownMenuLabel,
    DropdownMenuSeparator,
    DropdownMenuTrigger
} from "@/components/ui/dropdown-menu";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { cn } from "@/lib/utils";

export function ApiKeyMonitoring() {
    const [keys, setKeys] = useState<any[]>([]);
    const [loading, setLoading] = useState(true);
    const [page, setPage] = useState(1);
    const [meta, setMeta] = useState<any>(null);
    const [updating, setUpdating] = useState<string | null>(null);

    const fetchKeys = async () => {
        setLoading(true);
        try {
            const res = await fetch(`/api/admin/api-keys?page=${page}&limit=10`);
            const data = await res.json();
            setKeys(data.data);
            setMeta(data.meta);
        } catch (err) {
            console.error("Failed to fetch api keys:", err);
        } finally {
            setLoading(false);
        }
    };

    useEffect(() => {
        fetchKeys();
    }, [page]);

    const revokeKey = async (keyId: string) => {
        if (!confirm("Are you sure you want to revoke this API key? This action is permanent and will immediately break any integrations using this key.")) {
            return;
        }

        setUpdating(keyId);
        try {
            const res = await fetch(`/api/admin/api-keys/${keyId}/revoke`, {
                method: "POST"
            });

            if (res.ok) {
                setKeys(prev => prev.map(k => k.id === keyId ? { ...k, status: "revoked" } : k));
            } else {
                const errData = await res.json();
                alert(errData.error || "Failed to revoke API key");
            }
        } catch (err) {
            console.error("Error revoking key:", err);
        } finally {
            setUpdating(null);
        }
    };

    return (
        <div className="space-y-6">
            <div>
                <h1 className="text-3xl font-bold text-slate-900 tracking-tight">Global API Keys</h1>
                <p className="text-slate-500">Monitor and manage all API keys generated by users.</p>
            </div>

            <div className="bg-white rounded-xl border border-slate-200 shadow-sm overflow-hidden">
                <Table>
                    <TableHeader className="bg-slate-50/50">
                        <TableRow>
                            <TableHead>Key Name</TableHead>
                            <TableHead>Owner</TableHead>
                            <TableHead>Status</TableHead>
                            <TableHead>Last Used</TableHead>
                            <TableHead>Created</TableHead>
                            <TableHead className="text-right">Actions</TableHead>
                        </TableRow>
                    </TableHeader>
                    <TableBody>
                        {loading ? (
                            <TableRow>
                                <TableCell colSpan={6} className="h-24 text-center text-slate-500">
                                    <Loader2 className="h-6 w-6 animate-spin mx-auto mb-2" />
                                    Loading keys...
                                </TableCell>
                            </TableRow>
                        ) : keys.length === 0 ? (
                            <TableRow>
                                <TableCell colSpan={6} className="h-24 text-center text-slate-500">
                                    No API keys found.
                                </TableCell>
                            </TableRow>
                        ) : (
                            keys.map((key) => (
                                <TableRow key={key.id} className="hover:bg-slate-50/50 transition-colors">
                                    <TableCell>
                                        <div className="flex items-center gap-3">
                                            <div className="p-2 bg-slate-100 rounded-lg">
                                                <Key className="h-4 w-4 text-slate-600" />
                                            </div>
                                            <div className="font-semibold text-slate-900">{key.name}</div>
                                        </div>
                                    </TableCell>
                                    <TableCell>
                                        <div className="flex items-center gap-2">
                                            <User className="h-3 w-3 text-slate-400" />
                                            <span className="text-xs font-medium text-slate-700">{key.user?.email || "Unknown"}</span>
                                        </div>
                                    </TableCell>
                                    <TableCell>
                                        <Badge className={cn(
                                            "capitalize px-2 py-0.5 rounded-full border-none",
                                            key.status === "active" ? "bg-emerald-100 text-emerald-700" : "bg-rose-100 text-rose-700"
                                        )}>
                                            {key.status === "active" ? <CheckCircle2 className="h-3 w-3 mr-1 inline" /> : <Ban className="h-3 w-3 mr-1 inline" />}
                                            {key.status}
                                        </Badge>
                                    </TableCell>
                                    <TableCell>
                                        <div className="text-xs text-slate-500 flex items-center gap-1">
                                            <Activity className="h-3 w-3" />
                                            {key.lastUsedAt ? new Date(key.lastUsedAt).toLocaleDateString() : "Never"}
                                        </div>
                                    </TableCell>
                                    <TableCell>
                                        <div className="text-xs text-slate-500 flex items-center gap-1">
                                            <Calendar className="h-3 w-3" />
                                            {new Date(key.createdAt).toLocaleDateString()}
                                        </div>
                                    </TableCell>
                                    <TableCell className="text-right">
                                        <DropdownMenu>
                                            <DropdownMenuTrigger asChild>
                                                <Button variant="ghost" size="icon" disabled={updating === key.id}>
                                                    {updating === key.id ? <Loader2 className="h-4 w-4 animate-spin" /> : <MoreHorizontal className="h-4 w-4" />}
                                                </Button>
                                            </DropdownMenuTrigger>
                                            <DropdownMenuContent align="end" className="w-48">
                                                <DropdownMenuLabel>Key Management</DropdownMenuLabel>
                                                <DropdownMenuSeparator />
                                                <DropdownMenuItem
                                                    className="text-rose-600 focus:bg-rose-50"
                                                    disabled={key.status === "revoked"}
                                                    onClick={() => revokeKey(key.id)}
                                                >
                                                    <ShieldAlert className="h-4 w-4 mr-2" /> Revoke Key
                                                </DropdownMenuItem>
                                                <DropdownMenuSeparator />
                                                <DropdownMenuItem>View Usage History</DropdownMenuItem>
                                                <DropdownMenuItem>View Owner Profile</DropdownMenuItem>
                                            </DropdownMenuContent>
                                        </DropdownMenu>
                                    </TableCell>
                                </TableRow>
                            ))
                        )}
                    </TableBody>
                </Table>
            </div>

            {/* Pagination */}
            {meta && meta.totalPages > 1 && (
                <div className="flex items-center justify-between px-2">
                    <p className="text-sm text-slate-500 font-medium">
                        Showing page {page} of {meta.totalPages} ({meta.total} keys total)
                    </p>
                    <div className="flex items-center gap-2">
                        <Button
                            variant="outline"
                            size="sm"
                            onClick={() => setPage(p => Math.max(1, p - 1))}
                            disabled={page === 1}
                            className="border-slate-200"
                        >
                            <ChevronLeft className="h-4 w-4 mr-1" /> Previous
                        </Button>
                        <Button
                            variant="outline"
                            size="sm"
                            onClick={() => setPage(p => Math.min(meta.totalPages, p + 1))}
                            disabled={page === meta.totalPages}
                            className="border-slate-200"
                        >
                            Next <ChevronRight className="h-4 w-4 ml-1" />
                        </Button>
                    </div>
                </div>
            )}
        </div>
    );
}
